name: Build gig2sfz for Windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            libtool
            automake
            autoconf
            pkg-config

      - name: Build gig2sfz
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
          mingw32-make

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: gig2sfz-windows
          path: build/gig2sfz.exe
