name: Build gig2sfz Windows

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-libtool
            mingw-w64-x86_64-automake
            mingw-w64-x86_64-autoconf
            mingw-w64-x86_64-pkg-config

      - name: Build libgig
        shell: msys2 {0}
        run: |
          git clone https://github.com/linuxsampler/libgig.git
          cd libgig
          ./autogen.sh || true
          ./configure --prefix=/mingw64
          make -j$(nproc)
          make install

      - name: Build gig2sfz
        shell: msys2 {0}
        run: |
          cd $GITHUB_WORKSPACE
          make || (echo "Build failed" && exit 1)
          ls -l

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: gig2sfz-windows
          path: gig2sfz.exe
